/// Annual youth unemployment rates from ILO Table A.1.
table Rates
	lineageTag: 268edf34-f9de-4a38-a392-a55f0eee0279

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column RegionType
		dataType: string
		summarizeBy: none
		sourceColumn: RegionType

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column AgeGroup
		dataType: string
		summarizeBy: none
		sourceColumn: AgeGroup

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column YouthUnemploymentRate
		dataType: double
		formatString: 0.0%
		summarizeBy: none
		sourceColumn: YouthUnemploymentRate

		annotation SummarizationSetBy = Automatic

	column UnemployedPeople
		dataType: int64
		formatString: #,0
		summarizeBy: none
		sourceColumn: UnemployedPeople

		annotation SummarizationSetBy = Automatic

	column EstimateStatus
		dataType: string
		summarizeBy: none
		sourceColumn: EstimateStatus

		annotation SummarizationSetBy = Automatic

	/// Latest annual rate in the current region context. The year is fixed to 2025.
	measure 'Youth Unemployment Rate 2025' =
			CALCULATE (
				MAX ( Rates[YouthUnemploymentRate] ),
				Rates[Year] = 2025
			)
		formatString: 0.0%
		displayFolder: Headline metrics

	/// Global youth unemployment rate for 2025.
	measure 'World Youth Unemployment Rate 2025' =
			CALCULATE (
				[Youth Unemployment Rate 2025],
				REMOVEFILTERS ( Rates[Region], Rates[RegionType] ),
				Rates[Region] = "World"
			)
		formatString: 0.0%
		displayFolder: Headline metrics

	/// Approximate global count of unemployed youth reported by the ILO for 2025.
	measure 'Unemployed Youth 2025' =
			CALCULATE (
				MAX ( Rates[UnemployedPeople] ),
				REMOVEFILTERS ( Rates[Region], Rates[RegionType] ),
				Rates[Region] = "World",
				Rates[Year] = 2025
			)
		formatString: #,0,,"M"
		displayFolder: Headline metrics

	partition Rates = m
		mode: import
		source =
				let
					Source = Excel.Workbook(File.Contents(DataFilePath), null, true),
					RatesTable = Source{[Item = "YouthRates", Kind = "Table"]}[Data],
					Typed = Table.TransformColumnTypes(
						RatesTable,
						{
							{"Region", type text},
							{"RegionType", type text},
							{"Year", Int64.Type},
							{"AgeGroup", type text},
							{"Sex", type text},
							{"YouthUnemploymentRate", type number},
							{"UnemployedPeople", Int64.Type},
							{"EstimateStatus", type text}
						}
					)
				in
					Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
