/// Annual youth unemployment rates from ILO Table A.1.
table Rates
	lineageTag: 268edf34-f9de-4a38-a392-a55f0eee0279

	/// 2025 Total youth unemployment rate for exactly one geography. Year and Sex filters are overridden. Undefined multi-geography totals and no-matching-geography contexts return blank; rates are not additive.
	measure 'Youth Unemployment Rate 2025' =
			VAR _hasOneRegion =
			    CALCULATE (
			        HASONEVALUE ( 'Rates'[Region] ),
			        REMOVEFILTERS ( 'Rates'[Year], 'Rates'[Sex] )
			    )
			RETURN
			    IF (
			        _hasOneRegion,
			        CALCULATE (
			            SELECTEDVALUE ( 'Rates'[YouthUnemploymentRate] ),
			            'Rates'[Year] = 2025,
			            'Rates'[Sex] = "Total"
			        ),
			        BLANK ()
			    )
		formatString: 0.0%
		displayFolder: Headline metrics
		lineageTag: f5ab51e1-cfc1-4555-8ff0-b01ba3d9b151

	/// Fixed World 2025 Total rate for ages 15-24, independent of regional or other report selections. Source aggregate, not a sum or average of subregions.
	measure 'World Youth Unemployment Rate 2025' =
			CALCULATE (
			    SELECTEDVALUE ( 'Rates'[YouthUnemploymentRate] ),
			    REMOVEFILTERS ( 'Rates' ),
			    'Rates'[Region] = "World",
			    'Rates'[Year] = 2025,
			    'Rates'[Sex] = "Total",
			    'Rates'[AgeGroup] = "15-24"
			)
		formatString: 0.0%
		displayFolder: Headline metrics
		lineageTag: e0038f90-a774-44e9-b96f-8168ae449db9

	/// Fixed approximate World 2025 unemployed youth count in millions, ages 15-24. The stored 67M is a rounded ILO headline, not an exact individual count. Missing source counts remain blank.
	measure 'Unemployed Youth 2025' =
			VAR _worldCount =
			    CALCULATE (
			        SELECTEDVALUE ( 'Rates'[UnemployedPeople] ),
			        REMOVEFILTERS ( 'Rates' ),
			        'Rates'[Region] = "World",
			        'Rates'[Year] = 2025,
			        'Rates'[Sex] = "Total",
			        'Rates'[AgeGroup] = "15-24"
			    )
			RETURN
			    DIVIDE ( _worldCount, 1000000 )
		formatString: """≈ ""0""M"""
		displayFolder: Headline metrics
		lineageTag: d97d7255-61b7-42fe-850f-a3ac793cbbb4

	column Region
		dataType: string
		lineageTag: 765007ba-2ee8-4d72-9171-cf5a58fa07e9
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column RegionType
		dataType: string
		lineageTag: c5099f4c-3ace-4b2b-bccf-6b88dcc575f0
		summarizeBy: none
		sourceColumn: RegionType

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 3699e915-e72a-46a4-8952-63badee214cf
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column AgeGroup
		dataType: string
		lineageTag: 28f09346-b3e6-4ab0-a263-76dadcb1e257
		summarizeBy: none
		sourceColumn: AgeGroup

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: 5b2de512-29e2-4aeb-9186-8b537a6fb0b3
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column YouthUnemploymentRate
		dataType: double
		formatString: 0.0%
		lineageTag: 284d4249-3063-49c2-8291-db6771476295
		summarizeBy: none
		sourceColumn: YouthUnemploymentRate

		annotation SummarizationSetBy = Automatic

	column UnemployedPeople
		dataType: int64
		formatString: #,0
		lineageTag: 7d6ec202-2ed2-4859-a588-c908d647e143
		summarizeBy: none
		sourceColumn: UnemployedPeople

		annotation SummarizationSetBy = Automatic

	column EstimateStatus
		dataType: string
		lineageTag: 7dfba1b6-f2c7-49c6-9e9c-5cb916f5ad7e
		summarizeBy: none
		sourceColumn: EstimateStatus

		annotation SummarizationSetBy = Automatic

	/// Reviewed local Excel source; DataFilePath must be configured in the private copy before refresh.
	partition Rates = m
		mode: import
		source =
				let
					ConfiguredPath = if Text.Trim(DataFilePath) = "" then error Error.Record("DataFilePathNotConfigured", "Set the DataFilePath text parameter to the absolute path of the reviewed excel/youth-unemployment.xlsx before refreshing. See README local setup.", null) else DataFilePath,
					Source = Excel.Workbook(File.Contents(ConfiguredPath), null, true),
					RatesTable = Source{[Item = "YouthRates", Kind = "Table"]}[Data],
					Typed = Table.TransformColumnTypes(
						RatesTable,
						{
							{"Region", type text},
							{"RegionType", type text},
							{"Year", Int64.Type},
							{"AgeGroup", type text},
							{"Sex", type text},
							{"YouthUnemploymentRate", type number},
							{"UnemployedPeople", Int64.Type},
							{"EstimateStatus", type text}
						}
					)
				in
					Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
